version: '3.8'

services:
  postgres_service:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jason_network
    restart: always
    ports:
      - "6001:5432"

volumes:
  postgres_data:
    driver: local

networks:
  jason_network:
    name: jason
